### ISSUE TITLE
Using zotero URL protocol instead of URL?

### ISSUE THREAD

**Issue by argenos** [wbthomason/zotodo#2]
I just found this extension, and have been testing it out. Whenever tasks are created, the URL being used is that of the paper in question (e.g. pointing to IEEE Xplore). Is it possible to change this to use instead links with Zotero's protocol (e.g. zotero://open-pdf/library/items/3Z5GTF98?page=1). I tried changing the template to use the attachment path, but that does not open the file when clicked. 

Any tips? 

Thanks!

**Comment by wbthomason** [comment]
Hmm, I admit I wasn't aware of Zotero's protocol. Where have you seen that used otherwise? I'm curious when it would/wouldn't be handled.

If we can figure out where that protocol is/isn't valid, this should be easy enough to add as an option - it'll require getting any attachments for a new item, getting the key for those attachments, and then forming a `zotero://open-pdf/...` URL. It can be exposed as a new template key.

**Comment by argenos** [comment]
I also only recently found it by chance. The first place I saw it was testing out https://github.com/melat0nin/zotero-roam-export 
I haven't really found an official documentation page, but apparently it's possible to just select an item in the library (instead of opening the pdf). [This](https://zoteromusings.wordpress.com/2013/04/23/zotero-item-uris-from-client/#comment-13790) might help:

> Zotero Select
> 
> Zotero allows you to directly link to an item in your local database. If you paste a valid URI starting with zotero://select into your URL bar in Firefox, it will open Zotero to that item.  To create such a zotero://select link from an item, download the file “Zotero Select Item.js” from [here](https://github.com/Zotero-ODF-Scan/zotero-odf-scan/raw/master/attic/Zotero%20Select%20Item.js) and then follow steps 1-3 above. A link will look like zotero://select/items/0_USN95MJC and work only with your library

**Comment by wbthomason** [comment]
Thanks for the reference! I've added new tokens `pdf_id` and `item_id` to try and enable this. However, `zotero://select` and `zotero://open-pdf` links don't seem to work for me at all on my system - if you try out the latest zotodo version and can get a select link to work, please let me know.

This feature is also not quite perfect because the PDF ID will be -1 (i.e. invalid) if the PDF is added after the item is processed into a new task. Improving this would require tracking items with created tasks and updating them if they have a PDF attachment added, which seems fairly involved. As such, I'm not super likely to do so, particularly if select URIs for items work.

**Comment by argenos** [comment]
Thanks so much! I tested just now with v.0.4.0 and it works. Here's what I'm using:

- Ubuntu 18.04
- Zotero 5.0.88

My template looked like this: `Read "?${item_id}:[${title}](zotero://select/items/${item_id})?!${item_id}:${title}!"`

Let me know I can help any other way!

**Comment by argenos** [comment]
Oh damn, I spoke too soon and I think it was just a coincidence. I should have done more extensive testing before posting. 
When I tested with a few other items, it did not work. 

I did a bit more testing and from the WordPress post mentioned above I downloaded both `Item URI.js` and `Zotero Select Item.js`. And exported a few items using the `ctrl+shift+c`. I then pasted generated `zotero://select/items/<item_id>` in the browser. That opens Zotero if necessary, and does take me to the right item, regardless of the collection I am currently viewing or the item I have currently selected.

What I noticed is that the `item_id` in the Zotodo link is different. The ones generated with `ctrl+shif+c` usually start with a number and an underscore, e.g. `zotero://select/items/1_RKIR6SQV`. The part after the underscore also doesn't match the Zotodo `item_id`.

**Comment by wbthomason** [comment]
Hmm, ok. Does it work for you if you try `zotero://select/library/items/${item_id}`? That's the kind of link Zutilo generates for me. Unfortunately, that kind of link *also* doesn't work for me.

Did you have to do anything to set up handling of the `zotero://` protocol on your system? I did, and I'm wondering if I didn't get that set up correctly, which might explain why it doesn't seem to work for me.

**Comment by argenos** [comment]
Yep! That does it!

**Comment by argenos** [comment]
I was looking to set up the URL protocol manually until I found [zotero-deb](https://github.com/retorquere/zotero-deb) which took care of it for me. I do have a few links I can dig up, let me know if they would help.

**Comment by wbthomason** [comment]
Great! And thanks; by poking through the files in `zotero-deb` I was able to get it working on my machine!

Thank you for your help with this! I'll add a note on the README that this feature exists now.

**Comment by wbthomason** [comment]
Actually, I also added a `select_uri` template key so that you don't have to build the URI yourself (though `item_id` is still there if you want to).

**Comment by argenos** [comment]
Oh that's really nice! Thank you!
