### ISSUE TITLE
Error when trying to create task

### ISSUE THREAD

**Issue by tim-hilde** [wbthomason/zotodo#41]
I have been using the plugin for some time now but starting today I am constantly getting this error:

```
"Error requesting from https://api.todoist.com/rest/v1/projects: Gone <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title> 410 Gone</title><h1>Gone</h1> <p>This API endpoint is no longer available. Please refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com</p>
```

<img width="274" alt="image" src="https://user-images.githubusercontent.com/44113468/205669715-eede5cb0-c3b5-4c7a-a675-a50c70b41aad.png">

**Comment by wenlzhang** [comment]
I see similar errors.

**Comment by wbthomason** [comment]
Thanks for the report. I haven't been using `zotodo` myself, so I didn't notice. Let me see if there's a quick fix.

**Comment by InsiderPhD** [comment]
It looks like the v1 of the API has been deprecated, I have created a pull request: #43

**Comment by wbthomason** [comment]
@InsiderPhD: Thanks! I also discovered this and have a WIP fix, but: the Zotero plugin framework I used to build Zotodo has updated, which means that the old version no longer builds due to stale dependencies. I'm in the process of converting to the new architecture used by the framework, but haven't gotten everything working yet - in particular, Zotodo doesn't load, and I'm not sure why yet. I've put my WIP on this draft PR: https://github.com/wbthomason/zotodo/pull/44

I'll try to allocate time this week to continue debugging.

**Comment by WingerathM** [comment]
Just had the same error. So I wanted to thank you for the addon and just ask if you've made any progress?

**Comment by wbthomason** [comment]
Sorry, I haven't made much progress (or had much time to work on this).

**Comment by wbthomason** [comment]
@WingerathM Thanks for the nudge! I made time for this tonight and think I have things working. I'm going to merge #44 and put out a new release - please re-open this issue if the bug isn't fixed for you (or open new issues if my changes broke something else; TypeScript/the Zotero API are not tools I use frequently, so I may have made dumb errors)

**Comment by wbthomason** [comment]
Also if any of @tim-hilde @InsiderPhD @wenlzhang can confirm that #44 fixes the issue for them, that would be great. Thank you all for your help and patience!
